# Generated by Django 4.2 on 2023-04-29 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_todo_completion_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='host',
        ),
    ]
