# Generated by Django 4.2 on 2023-04-30 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_todo_completion_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='completion_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='task_time',
            field=models.CharField(blank=True, default='under', max_length=50, null=True),
        ),
    ]
