# Generated by Django 4.2 on 2023-04-30 16:38

from django.db import migrations, models
import user.utils


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_todo_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('In-Progress', 'PR'), ('Completed', 'CO')], default=user.utils.TodoStatus['PR'], max_length=50),
        ),
    ]
